apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-nio4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-nio4
    app.kubernetes.io/part-of: node-app
  name: devfile-sample-code-with-quarkus-nio4
  namespace: ssadeghi-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-nio4
status:
  loadBalancer: {}
