apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-ex-lehg
  namespace: ssadeghi-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:_5t0Z-nodejs-ex-lehg
        name: my-nodejs
        resources: {}
status: {}
