apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-ex-lehg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-ex-lehg
    app.kubernetes.io/part-of: node-app
  name: nodejs-ex-lehg
  namespace: ssadeghi-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs-ex-lehg
status:
  loadBalancer: {}
